name: madstonelab.com
favicon: null
layout_spectrum: 0.08698318153619766
typography_spectrum: 0.36886274721473455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.40220480342395604
  lightness: 0.608133350731805
  saturation: 0.5823849567677826
  rhythmicContrast: 0.5184058633167297
purpose: []
